import './globals.css'
import { Inter } from 'next/font/google'
import Navigationbar from '@/components/Navigationbar'
import Footer from '@/components/Footer';
import { Providers } from "./providers";
import { ClerkProvider } from '@clerk/nextjs'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'EXINES Lab | Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="!scroll-smooth">
        <body className={inter.className}>
          <Providers>
            <Navigationbar />
            <main className='min-h-screen flex flex-col'>
              {children}
            </main>
            <Footer />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
